language: elixir
elixir: '1.7'
otp_release: '21.2'

services:
  - docker
  - postgres

script:
  - MIX_ENV=test mix do deps.get, ecto.setup, test

deploy:
  # build latest tag
  - provider: script
    script: bash scripts/release_docker.sh latest
    on:
      branch: master

  # build version
  - provider: script
    script: bash scripts/release_docker.sh $TRAVIS_TAG
    on:
      tags: true
